import Link from "next/link";
import { notFound } from "next/navigation";
import Footer from "../../components/Footer";
import { lastUpdated, legalBusinessName, policies, registeredAddress, supportEmail } from "../../components/legal";

type Section = { heading: string; body: string[] };
const policyContent: Record<string, { intro: string; sections: Section[] }> = {
  "terms-of-use": { intro: "These Terms of Use govern websites, apps, software and other digital products operated by Lesedi Smart Solutions (Pty) Ltd (\"Lesedi\", \"we\", \"us\" or \"our\"). By using a product, you agree to these terms and any applicable product-specific terms.", sections: [{ heading: "Product-specific terms", body: ["Each Lesedi product may have its own product-specific terms, prices, fulfilment conditions, cancellation rules and support process. Where there is a conflict, the product-specific terms apply to that product."] }, { heading: "Using our products", body: ["Use our products lawfully, keep account credentials secure, provide accurate information, and do not interfere with a product’s security, availability or other users."] }, { heading: "Payments", body: ["Lesedi remains the legal entity processing payments where applicable. Payments may be securely processed by Paystack. We do not store full card numbers or CVV details."] }, { heading: "Changes and law", body: ["We may update these terms from time to time. These terms are governed by the laws of the Republic of South Africa, subject to applicable consumer-protection law."] }] },
  "privacy-policy": { intro: "This Privacy Policy explains how Lesedi Smart Solutions (Pty) Ltd collects, uses, shares and protects personal information when you use our websites, apps and digital products.", sections: [{ heading: "Information we collect", body: ["Depending on the product, we may collect contact and account details, information you provide, transaction and subscription information, device and usage data, and support communications."] }, { heading: "How we use information", body: ["We use information to provide and improve products, authenticate users, process transactions, provide support, prevent fraud and abuse, and meet legal obligations."] }, { heading: "Payments and sharing", body: ["Payments may be securely processed by Paystack. We do not store full card numbers or CVV details. We may use appropriately selected providers for hosting, analytics, communications and payment services. We do not sell personal information."] }, { heading: "Your choices", body: ["You may ask to access, correct or delete personal information, object to certain processing, or unsubscribe from marketing communications, subject to legal and operational limits."] }] },
  "refund-policy": { intro: "This policy describes our general approach to refunds for products provided by Lesedi Smart Solutions (Pty) Ltd. It applies alongside applicable law and product-specific terms.", sections: [{ heading: "Product-specific rules", body: ["Each product may set its own prices, fulfilment conditions, cancellation rules and support process. Product-specific refund terms shown at purchase or in the relevant product terms take priority for that product."] }, { heading: "Digital products and subscriptions", body: ["Eligibility depends on the product, purchase terms, whether delivery or access has started, and applicable consumer law. Cancelling a subscription stops future renewal where applicable; it does not automatically create a refund for a period already billed or used."] }, { heading: "Requesting a refund", body: ["Contact support with your order reference, product name, purchase email and a brief description of the issue. Approved refunds are generally returned to the original payment method."] }] },
  "shipping-delivery-policy": { intro: "Lesedi Smart Solutions (Pty) Ltd develops and operates digital products and apps. This policy explains our general fulfilment approach for digital products and any physical items offered through a specific product.", sections: [{ heading: "Digital delivery", body: ["Digital products, subscriptions and services are normally delivered through account access, email, download, activation or in-app access. Timing depends on the relevant product and may be immediate after successful payment or subject to verification, onboarding or a scheduled service period."] }, { heading: "Physical goods", body: ["If a product offers physical goods, its product page or checkout will state delivery areas, fees, estimated delivery times, tracking arrangements and restrictions. Delivery estimates are not guarantees."] }, { heading: "Payment and fulfilment", body: ["Lesedi remains the legal entity processing payments where applicable. Payments may be securely processed by Paystack, and we do not store full card numbers or CVV details."] }] },
  "cookie-policy": { intro: "This Cookie Policy explains how Lesedi Smart Solutions (Pty) Ltd uses cookies and similar technologies on our websites, apps and digital products.", sections: [{ heading: "How we use cookies", body: ["Depending on the product, we use strictly necessary cookies for core functions such as sign-in and security, preference cookies to remember settings, analytics cookies to understand performance and usage, and marketing cookies where permitted and used."] }, { heading: "Your controls", body: ["You can control or delete cookies through your browser settings. Blocking certain cookies may affect features such as sign-in, saved settings or checkout."] }, { heading: "Product-specific information", body: ["A Lesedi product may publish its own cookie notice or consent settings. Those product-specific details apply alongside this policy."] }] },
  "popia-data-privacy-policy": { intro: "Lesedi Smart Solutions (Pty) Ltd is committed to processing personal information responsibly. This notice describes our data-privacy approach under the Protection of Personal Information Act, 2013 (\"POPIA\"), where it applies.", sections: [{ heading: "Responsible party and purpose", body: ["Lesedi is generally the responsible party for personal information processed through its websites, apps and digital products. We process information to provide products and support, manage accounts and payments, protect security, improve services and meet legal obligations."] }, { heading: "Lawful processing and operators", body: ["We process personal information only where we have a lawful basis under POPIA. We may use appropriately selected operators and service providers, including payment providers such as Paystack where applicable."] }, { heading: "Your rights", body: ["Subject to POPIA and other applicable law, you may request access or correction, object to certain processing, withdraw consent where processing relies on consent, or lodge a complaint with the Information Regulator."] }] },
};

export function generateStaticParams() { return policies.map(({ slug }) => ({ slug })); }
export default async function PolicyPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const policy = policies.find((item) => item.slug === slug); const content = policyContent[slug]; if (!policy || !content) notFound();
  return <main className="legalSite"><header className="legalHeader"><Link href="/">Home</Link><Link href="/legal">Legal &amp; Policies</Link></header><article className="policyPage"><p className="dotLabel">Legal &amp; Policies</p><h1>{policy.title}</h1><p className="lastUpdated">Last updated: {lastUpdated}</p><p className="policyIntro">{content.intro}</p><div className="policyNotice">Each Lesedi product may have its own product-specific terms, prices, fulfilment conditions, cancellation rules and support process.</div>{content.sections.map((section) => <section key={section.heading}><h2>{section.heading}</h2>{section.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>)}<section className="policyContact"><h2>Contact us</h2><p>{legalBusinessName}</p><p><a href={`mailto:${supportEmail}`}>{supportEmail}</a></p><p>{registeredAddress}</p></section></article><Footer /></main>;
}
